# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice120202' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'

  # Pods for Practice1202

  target 'Practice120202Tests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

end